CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS HALL1
(
    ROW   INTEGER,
    PLACE INTEGER,
    ACC   INTEGER REFERENCES ACCOUNT (ID) ON DELETE CASCADE,
    CONSTRAINT unique_place UNIQUE (ROW, PLACE)
);
INSERT INTO ACCOUNT (ID, NAME)
VALUES (0, 'CINEMA')
ON CONFLICT (ID) DO UPDATE SET NAME ='CINEMA';